# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_auto_20160913_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='visited',
            field=models.BooleanField(default=0),
        ),
    ]
