# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_restaurant_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
