# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0006_auto_20160915_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.ManyToManyField(to='lunch.ReviewComment'),
        ),
    ]
